### ISSUE TITLE
Current release of loads.js doesn't load properly url entries on redis

### ISSUE THREAD

**Issue by remagio** [edsu/earls#13]
I'm confirming my comment on #9 "I'm still using the old version of loads.js. The old loads.js works fine with same json, delta tweets or full reload on a fresh earls. The current loads.js doesn't load entry in redis also if trying a fresh install.
You could check it by yourself with _your_ user, if planning it: to not brake the live instance of earls and using both current and old loads.js with the same json.

**Comment by edsu** [comment]
I don't understand this. Please provide a clear description of the problem, and how to reproduce it.

**Comment by remagio** [comment]
I verified, on the same instance you worked on, that current release of loads.js do not load all URLs of same twarc. But previous release of "loads.js" load it correctly.

To simulate your can _twarc_ #ijf15 and load it with current and previous _load.js_. Or verify it on the instance you know, with your active account.

**Comment by edsu** [comment]
Oh interesting, it looks like with long files it is exiting before the queue has been emptied? I've only been testing with small files and hadn't noticed this behavior before, thanks!

**Comment by remagio** [comment]
Ok, debugging I realized too it stops in something but without stopping the evaluate phase of json. It confused me. In this case the #ijf15 json is less than 1300 urls but nearly 1200 tweets.
