### ISSUE TITLE
Stopped updates or closed query connections vs Twitter

### ISSUE THREAD

**Issue by remagio** [edsu/earls#3]
Being an early user of earls I ran parallel twarc query and comparing it utils/urls.py to monitor same query. So, I found in the same days diffs between twarc's results and top's urls listed by earls.

My actual workaround is to flush earls redis queue/db and reload twarc results:
- without logs or error logs I cannot realize why/when an instance of earls stop "reading" tweets and indexing urls for relaunch a new flushall plus loadjs
- neither with unix cmd iftop I cannot see earls's connection vs twitter

imho, simple enhancement suggestions:
- include a redis flushall arguments with your loadjs, to support a cleanup and/or a reloads by twarc json
- store periodically the earls redis db for fresh/cleanup restart like alternative of managing parallel twarc query

**Comment by edsu** [comment]
I don't really want a load to wipe out what is in the db already. I could adjust it so that it doesn't load the same tweet more than once though if that is convenient.

**Comment by remagio** [comment]
Looks  a good fit, i was thinking about one line code but obviously your solutions solve many more issue/enhancement!

About my previous second point: for events on more days (like a 3-5 days conference), it could be useful to manage "per day" top urls (during live day conference). I see there are lots of way in introduce this, also keeping it simple (views for All, Today, this Week, ..).
Do you evaluated any cases like this without managing multiple instances ?

**Comment by edsu** [comment]
Lets' open a new ticket with that per-day feature request.
