### ISSUE TITLE
Does it support multiple URLs in the same tweets?

### ISSUE THREAD

**Issue by remagio** [edsu/earls#4]
I did a new earls instance about a query and used flushall redis command for fresh data:
- used loadjs of a twarc json to populate earls;
- launched earls instance and waiting 1h before tweet top 3 urls listed;
- tweeted top 3 urls of earls in the same tweet, including the query string for being scraped by earls;
- waited almost 1h but none of 3 url is added to earls, counters isn't updated
  What did I wrong?
  Or is it related to issue 3 https://github.com/edsu/earls/issues/3 ?

**Comment by edsu** [comment]
It may be that earls wasn't connected properly to Twitter? You should periodically see messages like this:

```
processing tweet: 567987676210704384
```

when it finds a tweet that matches your filter. And yes it does process all the URLs in the tweet: see [lines 123-132](https://github.com/edsu/earls/blob/master/earls.js#L123-132). 

If earls has trouble connecting to Twitter you should see an error message on the console starting with:

```
twitter problem: ...
```
