### ISSUE TITLE
Wrong Title when scraping of an URL's Title isn't using ENG encoding

### ISSUE THREAD

**Issue by remagio** [edsu/earls#8]
By example with french, spanish and so on. Here is attached an earls log about this issue:

```
tallying:  https://cipe.uclm.es/noticias/becas-amazon-el-pais-para-participar-en-el-festival-internacional-de-periodismo-2015/ Informaci�n de Becas Amazon-El Pa�s para participar en el Festival Internacional de Periodismo 2015 | CIPE UCLM - Centro de Informacion y Promoci�n del Empleo cipeuclm https://twitter.com/cipeuclm/statuses/571279936587227137
finished processing url: http://ht.ly/INEQp
```

Checking earls's source I found that cheerio is using defaults, like if all titles are using EN encoding. If I'm right I think it could be solved simply like on a typical nodejs scraping app like here: https://stackoverflow.com/questions/12326688/node-js-scrape-encoding. 
I haven't found the cheerio way, but this sample show how to get automatically the right encoding, without analyzing the site, in converting all request() to UTF-8:

```
request.get({url: 'http://www.example.com', encoding: 'binary'}, function(err, res, body) {
    enc = charset(res.headers, body)
    enc = enc or jchardet.detect(body).encoding.toLowerCase()
    if enc != 'utf-8'
        iconv = new Iconv(enc, 'UTF-8//TRANSLIT//IGNORE')
        html = iconv.convert(new Buffer(body, 'binary')).toString('utf-8')
    console.log(body);
});
```

**Comment by edsu** [comment]
Do they show up incorrectly in the web view? Perhaps this is just a console problem?

**Comment by remagio** [comment]
No, got the wrong title it appears everywhere wrong. Not only in console, in redis's query and web view

**Comment by edsu** [comment]
Strange, when I curl that url:

```
curl https://cipe.uclm.es/noticias/becas-amazon-el-pais-para-participar-en-el-festival-internacional-de-periodismo-2015/
```

I get a title like this:

``` html
<title>Informaci?n de Becas Amazon-El Pa?s para participar en el Festival Internacional de Periodismo 2015 | CIPE UCLM - Centro de Informacion y Promoci?n del Empleo</title>
```

I checked to see if sending User-Agent and Accept-Language will help with this one and it didn't seem to.

**Comment by remagio** [comment]
Weird, honestly I have to say that in a couple of day I covered with earls almost 200.000 URLs (same cases of nearly 2.000 users sharing same URL) and I haven't found other cases like that. Lots of "timeouts" or "unable to get title" but anyway links work fine.
Feel free to close this issue, it's up to you. Thx.
