### ISSUE TITLE
load.js do not exit

### ISSUE THREAD

**Issue by remagio** [edsu/earls#9]
Trying in managing a backup/balanced instance of earls but I have not found how to insert "node load.js" in automated task because it doesn't exit when finished. Is it still in development or kinda stable?

**Comment by edsu** [comment]
Can you please paste what you are doing and the error?

**Comment by remagio** [comment]
```
load.js file.json
```

It does the same on the command line, there are no error. When finished to load the json it waits without exit. Same instance you tested, it requires a CTRL-C.
_Update_: since the beginning. I awaited to open the issue until now: I'm trying to balance not earls but two systems with same earls & cfg behind a nginx.

**Comment by edsu** [comment]
Ahh, does your file just have one tweet in it?

**Comment by remagio** [comment]
Not one but hundreds of tweets.
I'm doing daily twarc to avoid any failure of the redis instance but it waits without exiting since ever

**Comment by edsu** [comment]
Thanks @remagio ! it turns out I needed to wait for the file to close and end the process :-)

**Comment by remagio** [comment]
I'm still using the old version of loads.js. Initially I thought it was my faults with ENV settings, but no entry are added to redis without any errors. 
I'm using multiple earls instances, each one owns his own settings and redis instance too: launching old loads.js works fine.
